Table of Contents:
1. Introduction
    * What is Python
    * Jupyter
    * Anaconda
    
    
2. Data Structures and Data Types in Python
    * Primitive 
        * Integers
        * Float
        * Boolean
        * Strings
    * Non-Primitive
        * Tuples
        * Dictionary
        * Sets
        * Lists
  
  
3. For/While Loops and If Statements


4. User Defined Functions


5. Independent Challenge Problems


# 1. Introduction 
**A. What is Python?**
- Freely available, general purpose programming language that can be used on any modern computer operating system.
- Used for: processing text, numbers, images, scientific data 
- Python is a standard tool for most modern computer scientists and businesses
- Python is an interpreted language - not converted to computer readable code before the program is run but at runtime
- It is object-oriented and implementation of objects and classes allows for the greater reuse of code and ease of maintanability.


- Some applications of Python :
    * Automating manual processes within a business
    * Reading and writing to MySQL
    * Web development
    * Working with files
    * Building a Predictive Model
    
Why learn it?
- Python is an excellent language for general purpose programming. It is easy to read, write and learn as compared to other languages.

**B. Jupyter Notebooks**

- The Jupyter Notebook application allows you to edit docuements that display the input and output of a Python or R langauge script. Once saved you can share these files with others (Python and R are included by default, but with customization, Notebook can run several other kernel enviornments)
- Jupyter Notebook runs on your local desktop, and when prompted to open, it will open in a new browser and display the file strcuture on your computer.
- You have the option to create a new folder or file, and then to also upload any folders or files.
- Great for wiriting exploratory code or one-off analyses

**C. Anaconda Distribution**

- Anaconda is a free and open-source distribution of the Python and R programming lanaguages for scientific computing (data science, machine learning applications, large-scale data processing, predictive analytics, etc.) that aims to simplify package management and deployment.
- Pacakage versions are managed by the package management system conda.
- The anaconda distribution is used by over 15 million users and includes more than 1500 popular data science packages suitable for Windows, Linux, and MacOS.
- You are mostly likely running a Jupyter Notebook through the Anaconda Distribution.

# 2. Data Structures and Data Types in Python

In [100]:
#First we are going to set a variable x to 6 and a variable y to 4 so we can perform some basic operations
# We are setting them as floats since they have decimals
x = 6.0
y = 4.0

## Basic Operations

In [2]:
print(x + y) # Addition
print(x - y) # Subtraction
print(x * y) # Multiplication
print(x / y) # Quotient
print(x % y) # Remainder
print(abs(x)) # Absolute Value
print( x**y) # Exponents

10.0
2.0
24.0
1.5
2.0
6.0
1296.0


# Primitive  
These are the most basic building blocks for data manipulation. They are different data types.



## Integers

- represent numeric data, negative and positive whole numbers

In [101]:
x=-4
y=12

In [102]:
x+y

8

In [103]:
x-y

-16

In [104]:
x/y

-0.3333333333333333

In [105]:
x**y

16777216

## Float

- refers to floating point number
- used for rational and decimals 


In [106]:
x=4.5
y=2

In [9]:
x+y

6.5

In [10]:
x-y

2.5

In [118]:
x/y

TypeError: unsupported operand type(s) for /: 'str' and 'str'

In [12]:
x**y

20.25

## Boolean


- can take up True or False
- interchangeable with 1 or 0
- used for comparison and conditional expressions

In [107]:
x=4.5
y=2.0

In [108]:
x==y

False

In [109]:
x>y

True

In [110]:
x = True
y = False
print(x==1)
print(y==0)
print(x+y)

True
True
1


## Strings 

In [111]:
# Strings
x = 'Car'
y = 'Truck'

x + '&'  + y

'Car&Truck'

In [112]:
# Repeat strings
x * 2

'CarCar'

In [19]:
# Return character using the index
# Python index starts at 0
z = 'Hello'
print(z[1])

e


In [20]:
# Print length of strings
len(z)

5

In [21]:
# String Concatenation
z  + ' ' + 'World' 

'Hello World'

In [22]:
# Range slicing
z1 = z[3:]

print(z1)

lo


In [23]:
# More slicing
w = 'Welcome'
z2 = z[0] + w[4:]
print(z2)

Home


In [113]:
# Strings can also be alpha-numeric characters and we use the + operation to concatenate strings
a = '4'
b = '2'

a + b

'42'

## Implicit Data Conversion

- compiler automatically handles data conversion

In [117]:
# Variables
x = 'Car'
y = 'Truck'
z = 'Hello'
w = 'Welcome'

x1int = 10
x2int = 3

In [115]:
# You see that python tried to divide these two variables but 
# couldn't convert them to floats so it didn't and throws an error
x/y

TypeError: unsupported operand type(s) for /: 'str' and 'str'

In [116]:
# You see that x1int and x2int are taken in as integers when the variable is set
print(type(x1int))
print(type(x2int))

<class 'int'>
<class 'int'>


In [28]:
# You see that python takes care of the data type conversion by changing 
# from an int to a float to make the division possible
print(x1int/x2int)
print(type(x1int/x2int))

3.3333333333333335
<class 'float'>


## Explicit Data Conversion

- Explicit Type Conversion is also called Type Casting, the data types of object are converted using predefined function by user.

In [29]:
# so here we try implicity
w = 2
v = "The Godfather: Part "
fave_movie = v + w

TypeError: can only concatenate str (not "int") to str

In [30]:
# now we try explicity by changing the integer to a str and then we are able to concatenate
w = 2
v = "The Godfather: Part "
fave_movie = v + str(w)
print(fave_movie)

The Godfather: Part 2


# Non-Primative

## Tuples

- a sequence of immutable (cannot be changed once created) Python objects
- tuples are sequences, just like lists
- the difference between a tuple and a list is the tuples cannot be changed, but lists can be changed 
- tuples use parentheses, whereas lists use square brackets

In [31]:
tuple1 = 0, 1, 1, 2 , 3, 5, 8, 13, 21, 34
print(tuple1)

(0, 1, 1, 2, 3, 5, 8, 13, 21, 34)


In [32]:
#you can grab a specific index in a tuple
print(tuple1[6])

8


In [33]:
# tuples like strings are immutable, you cannot change item 11 in the tuple to 55 once it has been created
tuple1[10] = 55

TypeError: 'tuple' object does not support item assignment

## Dictionary

- an unordered set of key: value pairs, with the requirement that the keys are unique (within one dictionary).
- a pair of braces creates an empty dictionary
- dictionaries are made up of key-value pairs.


In [119]:
# create a dictionary
s_dict = {'Jack':10, 'Jill':20, 'John':30, 'Jane': 40}
print(s_dict)

{'Jack': 10, 'Jill': 20, 'John': 30, 'Jane': 40}


In [121]:
# delete a value key pair from the dictionary
del s_dict['John']
print(s_dict)

{'Jack': 10, 'Jill': 20, 'Jane': 40}


In [43]:
# print the value stored in a key 
print(s_dict['Jane'])

40


Let's apply some inbuilt functionalities on dictionaries

In [122]:
# get the total count of key value pairs
len(s_dict)

3

In [38]:
# get all the keys from the dictionary without the values
s_dict.keys()

dict_keys(['Jack', 'Jill', 'Jane'])

In [39]:
# get all the values from the dictionary without the keys
s_dict.values()

dict_values([10, 20, 40])

## Sets

- collections of distinct(unique) objects
- it is an unordered collection data type that is iterable, mutable and has no duplicate elements
- major advantage of using a set instead of a list, is that it has highly optomized method for checking whether a specific element is contained in the set (based on a data strcuture known as a hash table)

In [45]:
x_set = set('CAKE&COOKIE')
y_set = set('COOKIE')

In [46]:
print(x_set)

{'&', 'E', 'C', 'K', 'A', 'I', 'O'}


In [47]:
print(y_set)

{'E', 'C', 'K', 'I', 'O'}


In [48]:
print(x_set|y_set) # Unique elements in x_set or y_set or both

{'&', 'E', 'C', 'K', 'A', 'I', 'O'}


In [49]:
# there are usually multiple ways to accomplish the same task in python

print(x_set & y_set) # Elements in both x_set and y_set
print(x_set.intersection(y_set)) # Elements in both x_set and y_set

{'E', 'C', 'K', 'I', 'O'}
{'E', 'C', 'K', 'I', 'O'}


In [50]:
# get all the elements in x_set that arent in y_set and vice versa
print(x_set.difference(y_set))
print(y_set.difference(x_set))

{'&', 'A'}
set()


In [51]:
# you can also add to a set
x_set.add('M')
print(x_set)

{'&', 'M', 'E', 'C', 'K', 'A', 'I', 'O'}


In [52]:
# you can also empty the whole set
x_set.clear()
print(x_set)

set()


## Files

- part of data structures
- type of big data commonplace in data science
- making use of data sitting in files across databases.

#### Some Python functions for working with files

read() - reads entire files

readline() -  to read one line at a time

write() - write to a string file

close() - close a file

In [123]:
# File modes (2nd argument) : 'r'(read), 'w'(write), 'a'(appending), 'r+'(both reading and writing)
f = open('file_name.txt','r+')

# Reads one line at a time
lines = f.readlines()

for line in lines:
    print(line.rstrip('\n'))
f.close()

This is the file.
Read it in line by line.
And see what each line says.


In [124]:
# Reads the entire file
# File modes (2nd argument) : 'r'(read), 'w'(write), 'a'(appending), 'r+'(both reading and writing)
f = open('file_name.txt','r+')
f.read()


'This is the file.\nRead it in line by line.\nAnd see what each line says.'

In [125]:
f.close()

In [129]:
# go check the file in the folder in jupyter, and you will see the new line appended
with open('file_name.txt', 'a') as f:
    f.write("\nThis is the last line in the file!")

## Arrays

- arrays and lists are both used in Python to store data, but they don't serve exactly the same purposes
- Both can be used to store any data type (real numbers, strings, etc.) and they both can be indexed and iterated through
- main difference is the functions that you can perform to them, and that all elements of the array must be of the same numeric type
- Python doesn't specifically have an array data-type built in (uses lists) so have to use a different library

In [130]:
#first we must import the numpy module to make working with arrays easier
import numpy as np
x = np.array([21,7,6,5])

In [58]:
print(x)

[21  7  6  5]


In [59]:
# you can append to an array
x = np.append(x, 41)
print(x)

[21  7  6  5 41]


In [60]:
# you can remove elements from an array based on position of the element
x = np.delete(x,0)
print(x)

[ 7  6  5 41]


In [61]:
# you can sort an array, sorts by ascending by default
x = np.sort(x)
print(x)

[ 5  6  7 41]


In [62]:
# you can make an array more than one dimension lets make a 2 by 4
y = np.array([[1,2,3,4], [5,6,7,8]])
print(y)

[[1 2 3 4]
 [5 6 7 8]]


In [63]:
# you can perform arthmitic on arrays if # of columns match up in both
print(x+y)
print('')
print(x-y)
print('')
print(x/y)

[[ 6  8 10 45]
 [10 12 14 49]]

[[ 4  4  4 37]
 [ 0  0  0 33]]

[[ 5.          3.          2.33333333 10.25      ]
 [ 1.          1.          1.          5.125     ]]


## Lists

- most versatile datatype availabe in Python which can be writte as a list of comma-seperated values (items) between square brackets
- Important thing about a list is that items in a list need NOT be of the same type

In [64]:
# you can slice and index lists
list1 = ['physics', 'chemistry', 1997, 2000]
list2 = [2,1,3,5,4,7,6]

print("list1[0]:", list1[0])
print("list2[1:5]:", list2[1:5])

list1[0]: physics
list2[1:5]: [1, 3, 5, 4]


In [65]:
# you can change items in a list by their index
list1[2] = 2001
print(list1)

['physics', 'chemistry', 2001, 2000]


In [66]:
# you can delete list items
del list1[2]
print(list1)

['physics', 'chemistry', 2000]


In [67]:
# you can take the length of a list, and it tells you how many items are in it
len(list2)

7

In [68]:
# you can concatanate lists or add them together
list3 = list1 + list2
print(list3)

['physics', 'chemistry', 2000, 2, 1, 3, 5, 4, 7, 6]


In [69]:
# you can append items to a list
list3.append('Daniel')
print(list3)

['physics', 'chemistry', 2000, 2, 1, 3, 5, 4, 7, 6, 'Daniel']


In [70]:
# you can sort a list if it is all integers 
list2.sort()
print(list2)

[1, 2, 3, 4, 5, 6, 7]


In [71]:
# you can sort a list if it is all strings
list4 = ['Gaby', 'Amber', 'Candie', 'Ronald']
list4.sort()
print(list4)

['Amber', 'Candie', 'Gaby', 'Ronald']


In [72]:
# you can check for membership (if an item is in the list)
print(3 in list2)
print(20 in list2)

True
False


# 3. For Loops and If Statements

## If Statements

Python supports the usual logical conditions from mathematics:

* Equals: a == b
* Not Equals: a != b
* Less than: a < b
* Less than or equal to: a <= b
* Greater than: a > b
* Greater than or equal to: a >= b

* Python relies on indentation (whitespace at the beginnin of a line or tab) to define scope in the code. It will automatically indent, but you may need to continue the indentation to make sure an error is not thrown
* elif can be used as a keyword in an if statement as pythons way of saying "if the previous condition were not true, then try this condition"
* the else keyword catches anything which isn't caught by the preceding conditions

Syntax for if statements is as follows:

if (expression):

    Statement   
else:

    Statement

In [131]:
# try changing up x and y to see the different outputs
x=10
y=8

if (x<y):
    st = 'x is less than y'
else:
    st = 'y is less than x'

print(st)
    


y is less than x


In [132]:
# you can also use an elif statement, we didnt think that they 
# could be the same in the above problem, but it is a possible condition, so we add that in
x=8
y=8

if (x<y):
    st = 'x is less than y'
elif (x==y):
    st = 'x and y are the same'
else:
    st = 'y is less than x'
    
print(st)

x and y are the same


In [75]:
# the 'and' keyword is a logical operator and can be used to combine conditional statements
x = 17
y = 14
z = 5
w = 5

if (x>y) and (z==w):
    print('X is greater than Y and Z is equal to W')
else:
    print("Oh no try to input different numbers!")

X is greater than Y and Z is equal to W


In [76]:
# the 'or' keyword is a logical operator used to cbomined conditional statements

if (x<y) or (z==w):
    print("One of your statements is correct!")
else:
    print("Both your statements are incorrect!")

One of your statements is correct!


In [134]:
# you can have a nested if, try changing the x variable starting number to see the output change
x = 15

if x > 10:
    print("Above 10,")
    if x > 20:
        print("and also above 20!")
    else:
        print("but not above 20")

Above 10,
but not above 20


In [78]:
# you can append to a list with an if statement

x = 22
listTest = []

if x > 10:
    listTest.append(x)
    print(listTest)
else:
    print("Sorry, not above 10")

[22]


## For Loops

A foor loop is used for iterating over a sequence (that is either a list, a tuple, a dictionary, a set, or a string). 

- This is less like the for keyword in other programing languages, and works more like an iterator method as found in other object-oriented programming languages
- with the for loop we can execute a set of statements, once for each item in a list, tuple, set, etc.

In [79]:
# looping through a list
fruits = ['apple', 'banana', 'cheery']

for x in fruits:
    print(x)

apple
banana
cheery


In [80]:
# looping through a string
for x in "banana":
    print(x)

b
a
n
a
n
a


With the break statement we can stop the loop before it has looped through all the items:
    

In [81]:
#  Exit the loop when x is "banana":

fruits = ["apple", "banana", "cherry"]

for x in fruits:
    print(x)
    if x == "banana":
        break

apple
banana


In [82]:
# Exit the loop when x is "banana", but this time the break comes before the print:

fruits = ["apple", "banana", "cherry"]

for x in fruits:
    if x == "banana":
        break
    print(x)

apple


The range() function is used to loop through a set of code a specified number of times
- The range() function returns a sequence of numbers, starting from 0 by default, and increments by 1 (by default), and ends at a specified number

In [83]:
for x in range(6):
    print(x)

0
1
2
3
4
5


In [84]:
# use the start parameter
for x in range(2,6):
    print(x)

2
3
4
5


In [85]:
# use the start and end paramter, and increment the sequence with 3 (default is 1)
for x in range(2,30,3):
    print(x)

2
5
8
11
14
17
20
23
26
29


Else in For Loop
- The else keyword in a for loop specified a block of code to be executed when the loop is finsihed

In [86]:
for x in range(6):
    print(x)
else:
    print("Finally finished!")

0
1
2
3
4
5
Finally finished!


In [87]:
# you can append to a list with a for loop
listTest = []
for x in range(0,12):
    listTest.append(x)
    print(listTest)

[0]
[0, 1]
[0, 1, 2]
[0, 1, 2, 3]
[0, 1, 2, 3, 4]
[0, 1, 2, 3, 4, 5]
[0, 1, 2, 3, 4, 5, 6]
[0, 1, 2, 3, 4, 5, 6, 7]
[0, 1, 2, 3, 4, 5, 6, 7, 8]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]


Nested Loops
- A nested loop is a loop inside a loop
- The "inner loop" will be executed one time for each iteration of the "outer loop"

In [88]:
# print each adjective for every fruit
adj = ["red", "big", "tasty"]
fruits = ["apple", "banana", "cherry"]

for x in adj:
    for y in fruits:
        print(x, y)

red apple
red banana
red cherry
big apple
big banana
big cherry
tasty apple
tasty banana
tasty cherry


## While Loops

With the while loop we can execute a set of statement as long as a condition is true.

- the while loop requires relevant variables to be ready, in this example we need to define an indexing variable i, which we set to 1
- we also have to manually increment in this instance with the += operation

In [89]:
i = 1
while i < 6:
    print(i)
    i += 2

1
3
5


With the continue statement we can stop the current iteration, and continue with the next

- NOTE: this is different from break as break stops the whole process, in this instance it just skips outputting the print statement for 3, but continues with the rest of the numbers

In [90]:
i = 0
while i < 6:
    i += 1
    if i == 3:
        continue
    print(i)

1
2
4
5
6


With the else statement we can run a block of code once when the condition is no loner true

In [91]:
i = 1
while i < 6:
    print(i)
    i += 1
else:
    print("i is no longer less than 6")

1
2
3
4
5
i is no longer less than 6


# User-Defined Functions in Python

- Functions are common in all programming languages and it can be defined as a block of re-usuable code to perform specific tasks.
- They only need to be written once and can be used multiple times.
- These functions are very useful, from writing common utilities to specific business logic.
- The code is usually well organized, easy to maintain, and developer-friendly.
- First you create a function, and then you call the function to use it.

## Function Definition

In [92]:
#Syntax of a function

def function_name(parameters):
    """docstring"""
    statement(s)
    return()

The function definition consists of the following components:
1. Keyword 'def' marks the start of a function header
2. A function name to uniquely identify it. Function naming follows the same rules of writing identifiers in Python.
3. Parameters (arguments) through which we pass values to a function.  They are optional.
4. A colon (:) to mark the end of a function header
5. Optional documentation string  (docstring) to describe what the function does
6. One or more valid python statements that make up the function body. Statements must have the same indentation level
7. An Optional return statement to return a value from the function

## Function Arguments

In python, user-defined function can take four different types of arguements. The argument types and their meaning, however, are pre defined and can't be changed.

1. Default Arguments:
    - Python has a different way of representing syntax and default values for function arguments. Default values indicate that the function argument will take that value if no argument value is passed during the function call. 
    - The default value is assigned by using the = operator. Below is typical syntax for a default argument. Here, 'msg' paramter has a default value "Hello!"

2. Required Arguments
    - Required arguments are the mandatory arguments of a fuction. These argument values must be passed in correct number and order during fuction call.
    - Below is a typical syntax for a required argument function.
   

3. Keyword Arguments
    - Keyword arguments are relevant for Python function calls.
    - The keywords are mentioned during the function call along with their corresponding values.
    - These keywords are mapped with the function arguments so the function can easily identify the corresponding values even if the order is not maintained during the function call.

## Example of a function

In [135]:
# function definintion
def greet(name="Bill"):
    """This function greets to the person passed in as paramter"""
    print("Hello, " + name + ". Good Morning!")

In [137]:
# function call
greet()

Hello, Bill. Good Morning!


## Example of a Default Function

In [95]:
def defArgFunc(empname, emprole = "Manager" ):  
    """this function takes in two parameters, with the emprole
    given a default and print out the name and the role"""
    print("Emp Name: ", empname)
    print("Emp Role: ", emprole)
    return;

# Deafult function call
defArgFunc(empname="Nick")

print('*****************')

#Overriding the default function call
defArgFunc(empname="Tom",emprole = "CEO")

Emp Name:  Nick
Emp Role:  Manager
*****************
Emp Name:  Tom
Emp Role:  CEO


## Example of Required Argument Function

In [96]:
def reqArgFunc(empname):   
    print ("Emp Name: ", empname)
    return   

# not passing required arg
reqArgFunc()

TypeError: reqArgFunc() missing 1 required positional argument: 'empname'

In [97]:
# Passing required arg
reqArgFunc("David")

Emp Name:  David


In [98]:
def keyArgFunc(empname, emprole):   
    print ("Emp Name: ", empname)
    print ("Emp Role: ", emprole)
    return  


# calling in the correct sequence
keyArgFunc(empname = "Nick",emprole = "Manager" )

print("**************")

# calling in a sequence out of order
keyArgFunc(emprole = "Manager",empname = "Nick")

Emp Name:  Nick
Emp Role:  Manager
**************
Emp Name:  Nick
Emp Role:  Manager


## Example of For and If statement in Function

In [99]:
# creating the function
def forAndIfStatement(lista, listb):
    if len(lista) > 5:
        for x in lista:
            print(x)
    elif len(lista) < 5:
        for y in listb:
            print(y)
    else:
        print("Your list length is equal to 5!")
        
# setting out variables        
listTesta = [1,2,3,4,5]
listTestb = [6,7,8,9,10,11,12,13]
listTestc = [1,2,3,6]

# call the function
forAndIfStatement(listTesta, listTestb)

print("**************")

# call the funtion
forAndIfStatement(listTestb, listTestc)

print("**************")

# call the function
forAndIfStatement(listTestc, listTesta)



Your list length is equal to 5!
**************
6
7
8
9
10
11
12
13
**************
1
2
3
4
5


# Your Turn to Practice!

Try your hand at these challenges problems. Send your solutions to Becky - bcrawford@sensecorp.com

Feel free to reach out to her with questions if you get stuck!

1.  Write a python function to sum all the numbers in a list, and print out the sum.

    * Do not use the sum() function

2. Write a python function to return the square or the cube of a number. This function should have 2 arguments: a number and power

3. Write a function that changes degrees from F to C, and prints out the numeric result

    * the input should be the degrees in F so a float or int
    * the output should be the degrees in C as a float or int
    * Do not round to a whole number; round to two decimal points in the output

4. Write a function that takes in one number and returns "odd" for odd numbers and "even" for even numbers

5. Write a function for checking the speed of drivers. This function should have one parameter: speed.
    * If speed is less than 70, it should print “Ok”.
    * Otherwise, for every 5mph above the speed limit (70), it should give the driver one demerit point and print the total number of demerit points. 
        * For example, if the speed is 80, it should print: “Points: 2”.
    * If the driver gets more than 12 points, the function should print: “License suspended”

6. Using the odd/even function from number 4, create a function that multiplies even numbers by 2 and squares odd numbers